name: moment_journey
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  avatar_glow: ^2.0.2
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  go_router: ^4.1.0
  highlight_text: ^1.4.0
  hive: ^2.2.3
  image_picker: ^0.8.5+3
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  logger: ^1.1.0
  permission_handler: ^10.0.0
  provider: ^6.0.3
  retrofit: ^3.0.1+1
  retrofit_generator: ^4.0.2
  speech_to_text: ^5.6.0
  zefyrka: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.0.5
  json_serializable: ^6.3.1
  injectable_generator: ^1.5.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - config/
